backend: compose
env-file: .envs/.env
defaults:
  group: ${{ env.SUGAR_GROUP }}
  project-name: mhai

hooks:
  pre-run:
    - name: collectstatic
      targets:
        compose:
          - build
          - start
          - restart
          - up
        compose-ext:
          - build
          - start
          - restart
          - up
      run: |
        makim django.collectstatic

groups:
  dev:
    config-path:
      - containers/compose.base.yaml
      - containers/compose.dev.yaml
    env-file: .envs/.env
    services:
      default: mhai-web,postgres,mailpit,redis,celeryworker,celerybeat,flower
      available:
        - name: mhai-web
        - name: postgres
        - name: mailpit
        - name: redis
        - name: celeryworker
        - name: celerybeat
        - name: flower

  test:
    config-path:
      - containers/compose.base.yaml
      - containers/compose.dev.yaml
    env-file: .envs/.env
    services:
      default: postgres,redis
      available:
        - name: postgres
        - name: redis

  prod:
    config-path:
      - containers/compose.base.yaml
      - containers/compose.prod.yaml
    env-file: .envs/.env
    services:
      default: mhai-web,postgres,redis,celeryworker,celerybeat,flower,nginx
      available:
        - name: mhai-web
        - name: postgres
        - name: redis
        - name: celeryworker
        - name: celerybeat
        - name: flower
        # - name: traefik
        - name: nginx
