#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

sudo chown -R 1000:1000 /opt/services/seconddx-web/src

cd /opt/services/seconddx-web/src/backend

python manage.py collectstatic --noinput

compress_enabled() {
python << END
import sys

from environ import Env

env = Env(COMPRESS_ENABLED=(bool, True))
if env('COMPRESS_ENABLED'):
    sys.exit(0)
else:
    sys.exit(1)

END
}

if compress_enabled; then
  # NOTE this command will fail if django-compressor is disabled
  python manage.py compress
fi
exec gunicorn config.asgi --bind 0.0.0.0:8000 --chdir=. -k uvicorn_worker.UvicornWorker
